[versions]
kotlin = "2.3.0-Beta2"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
komok-tech = "1.0.13"
logback = "1.5.20"
mcp = "0.7.7"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
komok-tech-logging = { module = "io.heapy.komok:komok-tech-logging", version.ref = "komok-tech" }
komok-tech-config-dotenv = { module = "io.heapy.komok:komok-tech-config-dotenv", version.ref = "komok-tech" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mcp-kotlin-sdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
